version: "3.9"

networks:
  spotlyt:
    driver: bridge

services:
  auth-service:
    container_name: auth-service
    build:
      context: ./
      cache_from:
        - base-image:nx-base
      dockerfile: ./apps/auth-service/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
        PORT: 7001
    image: auth-service:nx-dev
    hostname: auth-service
    ports:
      - "7001:7001"
    environment:
      NODE_ENV: "development"
      PORT: 7001
    networks:
      - spotlyt
    depends_on:
      - postgres
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7001/status/health" ]
      interval: 10s
      timeout: 10s
      retries: 10

  core-service:
    container_name: core-service
    build:
      context: ./
      cache_from:
        - base-image:nx-base
      dockerfile: ./apps/core-service/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
        PORT: 3000
    image: core-service:nx-dev
    hostname: core-service
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"
      PORT: 3000
    networks:
      - spotlyt
    depends_on:
      - postgres
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/status/health" ]
      interval: 10s
      timeout: 10s
      retries: 10

  media-service:
    container_name: media-service
    build:
      context: ./
      cache_from:
        - base-image:nx-base
      dockerfile: ./apps/media-service/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
        PORT: 7004
    image: media-service:nx-dev
    hostname: media-service
    ports:
      - "7004:7004"
    environment:
      NODE_ENV: "development"
      PORT: 7004
    networks:
      - spotlyt
    depends_on:
      - postgres
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7004/status/health"]
      interval: 10s
      timeout: 10s
      retries: 10

  kong:
    build:
      context: ./docker/kong
      dockerfile: Dockerfile
    container_name: kong
    restart: unless-stopped
    command: "kong start"
    volumes:
      - ./docker/kong/conf/kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - spotlyt

  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./docker/postgres/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    networks:
      - spotlyt
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@spotlyt.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
       - ./docker/postgres/docker_pgadmin_servers.json:/pgadmin4/servers.json

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'postgres:5432:*:postgres:password' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    networks:
      - spotlyt
    restart: unless-stopped

volumes:
    postgres:
    pgadmin: