_format_version: "2.1"
_transform: true

services:
  - name: auth-service
    url: http://auth-service:7001
    routes:
      - name: auth-service
        paths:
          - /auth
  - name: core-service
    url: http://core-service:3000
    routes:
      - name: core-service
        paths:
          - /core
  - name: media-service
    url: http://media-service:7004
    routes:
      - name: media-service
        paths:
          - /media

plugins:
  - name: rate-limiting
    service: core-service
    config:
      minute: 6 # The number of HTTP requests that can be made per minute
      policy: local